<?php

/**
 * @file
 */

/**
 * Implements hook_menu().
 */
function commerce_invoice_ui_menu() {
  $items = array();
  
  $items['admin/commerce/config/invoice'] = array(
    'title' => 'Invoice settings',
    'description' => 'Configure general invoice settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_invoice_settings_form'),
    'access arguments' => array('administer invoices'),
    'file' => 'includes/commerce_invoice_ui.invoices.inc',
  );
  $items['admin/commerce/config/invoice/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  return $items;
}

/**
 * Implements hook_views_api().
 */
function commerce_invoice_ui_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_invoice_ui') . '/includes/views',
  );
}
